apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: usearch-benchmark
  namespace: default
spec:
  type: Java
  mode: cluster
  image: usearch-spark:latest
  imagePullPolicy: Never
  mainClass: com.ashvardanian.USearchSpark
  mainApplicationFile: "local:///opt/spark/examples/jars/usearch-spark.jar"
  arguments:
    - "wiki"
    - "--max-vectors=10000"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never
  driver:
    cores: 2
    memory: "2g"
    labels:
      version: 3.5.1
    serviceAccount: spark-operator-spark
  executor:
    cores: 2
    instances: 2
    memory: "2g"
    labels:
      version: 3.5.1